-- Esquema base Espacios

-- PostgreSQL ejecuta este script solo al crear la bd por primera vez
-- con el volumen vacio. Para aplicar cambios, docker compose down -v

------------------------------------------------------------------------------
-- Salas
------------------------------------------------------------------------------

CREATE TABLE salas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    capacidad INTEGER NOT NULL CHECK (capacidad > 0)
);

------------------------------------------------------------------------------
-- Bloques horarios
------------------------------------------------------------------------------

CREATE TABLE bloques (
    hora_inicio TIME PRIMARY KEY,
    hora_fin TIME NOT NULL,
    CHECK (hora_fin > hora_inicio)
);

------------------------------------------------------------------------------
-- Ocupaciones (una fila por referencia, activa o liberada)
------------------------------------------------------------------------------
-- La referencia es la primary key ya que es lo que hace idempotente ocupar y
-- liberar. Las filas LIBERADA se conservan para rechazar ocupaciones tardias.
-- Si se libera una referencia que nunca ocupo, se guarda una fila LIBERADA
-- sin sala ni franja, por eso las columnas admiten NULL.

CREATE TABLE ocupaciones (
    referencia TEXT PRIMARY KEY,
    estado TEXT NOT NULL CHECK (estado IN ('ACTIVA', 'LIBERADA')),
    sala_id BIGINT REFERENCES salas(id),
    fecha DATE,
    hora_inicio TIME,
    hora_fin TIME,
    creada_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    liberada_en TIMESTAMPTZ,
    -- una ocupacion activa siempre dice que sala y franja ocupa
    CONSTRAINT ocupacion_activa_completa CHECK(
        estado <> 'ACTIVA'
        OR (sala_id IS NOT NULL AND fecha IS NOT NULL
            AND hora_inicio IS NOT NULL AND hora_fin IS NOT NULL)
    )
);


-- Sirve al conteo de puestos ocupados de una sala en una franja
-- Parcial, solo las activas cuentan, las liberadas no ocupan espacio en el indice
CREATE INDEX ocupaciones_activas_por_franja
    ON ocupaciones (sala_id, fecha, hora_inicio)
    WHERE estado = 'ACTIVA';